spring:
  redis:
    host: localhost
    port: 16379
  # Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.31.106:3306/database_name?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
#    username: sg
#    password: Ssg-DKJ832-QSEF
    url: jdbc:mysql://localhost:3306/learn_ls?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
