spring:
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      database: xh
      port: 27017
      host: 127.0.0.1
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  # Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.106:3306/lansen?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: sg
    password: Ssg-DKJ832-QSEF
#    url: jdbc:mysql://localhost:3306/learn_ls?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
#    username: root
#    password: root

