spring:
  cloud:
    gateway:
      discovery: #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:
          enabled: true  #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId
      default-filters: # 全局处理需要 default-filters
        - StripPrefix=2 # 处理predicates 路径
      routes:
        - id: xh-export
          uri: lb://XH-EXPORT # 根据注册中西 applicationname查找服务
          predicates:
            - Path=/api/export/*
        - id: xh-author
          uri: lb://XH-AUTHOR
          predicates:
            - Path=/api/auth/*
        - id: xh-mes
          uri: lb://XH-MESSAGE
          predicates:
            - Path=/api/mes/* # path 可以和predicates对应  缩进没有要求
